import Link from "next/link";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service | AuraFit",
  description: "Terms and conditions for using AuraFit's AI style analysis service.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-32 pb-24 px-6 md:px-12 max-w-3xl mx-auto">
        <header className="mb-16">
          <span className="font-label text-[10px] tracking-[0.3em] uppercase text-primary mb-4 block">Legal</span>
          <h1 className="font-headline text-5xl mb-6">Terms of Service</h1>
          <p className="font-body text-on-surface-variant">Last updated: May 2026</p>
        </header>

        <div className="space-y-12">

          <section className="bg-surface-container-low rounded-xl p-8">
            <p className="font-body text-sm text-on-surface-variant leading-relaxed">
              By using AuraFit, you agree to these terms. Please read them carefully — they&apos;re written in plain language. If you have questions, email{" "}
              <a href="mailto:hello@aurafit.fun" className="text-primary underline underline-offset-4">hello@aurafit.fun</a>.
            </p>
          </section>

          <TermsSection title="1. What AuraFit does">
            <p>
              AuraFit is an AI-powered style analysis service. You upload photos of yourself; our system analyzes your physical attributes (skin tone, body type, face shape) and generates personalized fashion recommendations.
            </p>
            <p>
              AuraFit is a <strong>fashion and style tool only</strong>. It is not a medical service, diagnostic tool, or health platform. No analysis or recommendation constitutes medical, cosmetic surgery, or dermatological advice.
            </p>
          </TermsSection>

          <TermsSection title="2. Eligibility">
            <ul>
              <li>You must be at least <strong>13 years old</strong> to use AuraFit.</li>
              <li>If you are under 18, you must have parental or guardian consent.</li>
              <li>By using AuraFit, you confirm that the photos you upload are of yourself or that you have explicit consent from the photographed person.</li>
            </ul>
          </TermsSection>

          <TermsSection title="3. Acceptable use">
            <p>You agree not to:</p>
            <ul>
              <li>Upload photos of other people without their consent</li>
              <li>Upload explicit, illegal, or harmful content</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the service</li>
              <li>Use automated bots to submit analysis requests</li>
              <li>Attempt to bypass rate limits or cost controls</li>
              <li>Use the service for any purpose that violates applicable law</li>
            </ul>
            <p>We reserve the right to terminate accounts that violate these terms without notice.</p>
          </TermsSection>

          <TermsSection title="4. AI-generated content disclaimer">
            <p>
              AuraFit&apos;s recommendations are generated by artificial intelligence and are <strong>not guaranteed to be accurate or suitable</strong> for every individual. Results may vary based on photo quality, lighting, and the inherent limitations of AI vision analysis.
            </p>
            <p>
              Style suggestions related to facial features, hairstyles, or body proportions are <strong>purely aesthetic and non-medical</strong>. We use body-positive, empowering language and do not generate harmful attractiveness scores or rankings.
            </p>
            <p>
              For any cosmetic procedure, surgical intervention, or medical decision, always consult a qualified professional. AuraFit accepts no liability for decisions made based on AI-generated style suggestions.
            </p>
          </TermsSection>

          <TermsSection title="5. Photo ownership & license">
            <p>
              You retain full ownership of any photos you upload. By uploading photos, you grant AuraFit a limited, temporary license to process those photos solely to generate your style analysis.
            </p>
            <p>
              This license ends when your photos are deleted (within 30 days, or earlier on request). We will never use your photos to train AI models, sell them, or display them publicly.
            </p>
          </TermsSection>

          <TermsSection title="6. Intellectual property">
            <p>
              Your style analysis results, color palettes, and wardrobe recommendations are generated for your personal use. You may share your results freely. AuraFit retains ownership of the underlying system, design, and AI prompts.
            </p>
          </TermsSection>

          <TermsSection title="7. Service availability">
            <p>
              AuraFit is provided &quot;as is&quot; without warranties of any kind. We do not guarantee 100% uptime. We may modify or discontinue features with reasonable notice.
            </p>
            <p>
              AI analysis quality depends on photo quality, lighting, and the capabilities of third-party AI providers. We cannot guarantee identical results across different photos or sessions.
            </p>
          </TermsSection>

          <TermsSection title="8. Limitation of liability">
            <p>
              To the fullest extent permitted by law, AuraFit is not liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to:
            </p>
            <ul>
              <li>Decisions made based on style recommendations</li>
              <li>Purchases made from linked external retailers</li>
              <li>Service outages or data loss</li>
            </ul>
          </TermsSection>

          <TermsSection title="9. Changes to these terms">
            <p>
              We may update these terms from time to time. We will notify registered users by email when significant changes are made. Continued use of AuraFit after changes constitutes acceptance.
            </p>
          </TermsSection>

          <TermsSection title="10. Contact">
            <p>
              Questions about these terms?{" "}
              <a href="mailto:hello@aurafit.fun" className="text-primary underline underline-offset-4">
                hello@aurafit.fun
              </a>
            </p>
          </TermsSection>

        </div>

        <div className="mt-16 pt-8 border-t border-outline-variant/30 flex gap-6">
          <Link href="/privacy" className="font-label text-xs uppercase tracking-widest text-on-surface-variant hover:text-primary transition-colors">
            Privacy Policy
          </Link>
          <Link href="/contact" className="font-label text-xs uppercase tracking-widest text-on-surface-variant hover:text-primary transition-colors">
            Contact
          </Link>
        </div>
      </main>
      <Footer />
    </>
  );
}

function TermsSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-headline text-2xl mb-5 text-on-surface">{title}</h2>
      <div className="font-body text-sm text-on-surface-variant leading-relaxed space-y-4 [&_ul]:space-y-2 [&_ul]:pl-4 [&_li]:leading-relaxed [&_strong]:text-on-surface">
        {children}
      </div>
    </section>
  );
}
